spring:
  application:
    name: sample-api
  jackson:
    serialization:
      write_dates_as_timestamps: false
  banner:
    location: banner.txt
  data:
    mongodb:
      uri: mongodb+srv://${user}:${password}@${host}/${database}?retryWrites=true&w=majority&maxIdleTimeMS=30000

server:
  servlet:
    context-path: /api/sample-services
    encoding:
      charset: UTF-8
      enabled: true
  port: 8080

springdoc:
  api-docs:
    enabled: true

management:
  server.ssl.enabled: false
  info:
    build.enabled: true
    defaults.enabled: true
  endpoints:
    web.base-path: /actuator
    web.exposure.include: 'health'
    shutdown.enabled: true
    health:
      show-details: always
  endpoint:
    health.enabled: true
    metrics.enabled: true
    heapdump.enabled: true
    mongo.enabled: true
  health:
    defaults.enabled: true
    diskspace.enabled: true
    jms.enabled: false
    mongo.enabled: false
    rabbit.enabled: false
    redis.enabled: false
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
  build:
    groupId: '@project.groupId@'
    artifact: '@project.artifactId@'
    name: '@project.name@'
    version: '@project.version@'
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}